import { Division, District } from '../types';

export const DIVISIONS: Division[] = [
  { id: '1', name: 'Dhaka', bnName: 'ঢাকা' },
  { id: '2', name: 'Chattogram', bnName: 'চট্টগ্রাম' },
  { id: '3', name: 'Rajshahi', bnName: 'রাজশাহী' },
  { id: '4', name: 'Khulna', bnName: 'খুলনা' },
  { id: '5', name: 'Barishal', bnName: 'বরিশাল' },
  { id: '6', name: 'Sylhet', bnName: 'সিলেট' },
  { id: '7', name: 'Rangpur', bnName: 'রংপুর' },
  { id: '8', name: 'Mymensingh', bnName: 'ময়মনসিংহ' },
];

export const DISTRICTS: District[] = [
  // Barishal
  { id: '1', divisionId: '5', name: 'Barguna', bnName: 'বরগুনা' },
  { id: '2', divisionId: '5', name: 'Barishal', bnName: 'বরিশাল' },
  { id: '3', divisionId: '5', name: 'Bhola', bnName: 'ভোলা' },
  { id: '4', divisionId: '5', name: 'Jhalokati', bnName: 'ঝালকাঠি' },
  { id: '5', divisionId: '5', name: 'Patuakhali', bnName: 'পটুয়াখালী' },
  { id: '6', divisionId: '5', name: 'Pirojpur', bnName: 'পিরোজপুর' },
  // Chattogram
  { id: '7', divisionId: '2', name: 'Bandarban', bnName: 'বান্দরবান' },
  { id: '8', divisionId: '2', name: 'Brahmanbaria', bnName: 'ব্রাহ্মণবাড়িয়া' },
  { id: '9', divisionId: '2', name: 'Chandpur', bnName: 'চাঁদপুর' },
  { id: '10', divisionId: '2', name: 'Chattogram', bnName: 'চট্টগ্রাম' },
  { id: '11', divisionId: '2', name: 'Cumilla', bnName: 'কুমিল্লা' },
  { id: '12', divisionId: '2', name: 'Cox\'s Bazar', bnName: 'কক্সবাজার' },
  { id: '13', divisionId: '2', name: 'Feni', bnName: 'ফেনী' },
  { id: '14', divisionId: '2', name: 'Khagrachhari', bnName: 'খাগড়াছড়ি' },
  { id: '15', divisionId: '2', name: 'Lakshmipur', bnName: 'লক্ষ্মীপুর' },
  { id: '16', divisionId: '2', name: 'Noakhali', bnName: 'নোয়াখালী' },
  { id: '17', divisionId: '2', name: 'Rangamati', bnName: 'রাঙ্গামাটি' },
  // Dhaka
  { id: '18', divisionId: '1', name: 'Dhaka', bnName: 'ঢাকা' },
  { id: '19', divisionId: '1', name: 'Faridpur', bnName: 'ফরিদপুর' },
  { id: '20', divisionId: '1', name: 'Gazipur', bnName: 'গাজীপুর' },
  { id: '21', divisionId: '1', name: 'Gopalganj', bnName: 'গোপালগঞ্জ' },
  { id: '22', divisionId: '1', name: 'Kishoreganj', bnName: 'কিশোরগঞ্জ' },
  { id: '23', divisionId: '1', name: 'Madaripur', bnName: 'মাদারীপুর' },
  { id: '24', divisionId: '1', name: 'Manikganj', bnName: 'মানিকগঞ্জ' },
  { id: '25', divisionId: '1', name: 'Munshiganj', bnName: 'মুন্সীগঞ্জ' },
  { id: '26', divisionId: '1', name: 'Narayanganj', bnName: 'নারায়ণগঞ্জ' },
  { id: '27', divisionId: '1', name: 'Narsingdi', bnName: 'নরসিংদী' },
  { id: '28', divisionId: '1', name: 'Rajbari', bnName: 'রাজবাড়ী' },
  { id: '29', divisionId: '1', name: 'Shariatpur', bnName: 'শরীয়তপুর' },
  { id: '30', divisionId: '1', name: 'Tangail', bnName: 'টাঙ্গাইল' },
  // Khulna
  { id: '31', divisionId: '4', name: 'Bagerhat', bnName: 'বাগেরহাট' },
  { id: '32', divisionId: '4', name: 'Chuadanga', bnName: 'চুয়াডাঙ্গা' },
  { id: '33', divisionId: '4', name: 'Jessore', bnName: 'যশোর' },
  { id: '34', divisionId: '4', name: 'Jhenaidah', bnName: 'ঝিনাইদহ' },
  { id: '35', divisionId: '4', name: 'Khulna', bnName: 'খুলনা' },
  { id: '36', divisionId: '4', name: 'Kushtia', bnName: 'কুষ্টিয়া' },
  { id: '37', divisionId: '4', name: 'Magura', bnName: 'মাগুরা' },
  { id: '38', divisionId: '4', name: 'Meherpur', bnName: 'মেহেরপুর' },
  { id: '39', divisionId: '4', name: 'Narail', bnName: 'নড়াইল' },
  { id: '40', divisionId: '4', name: 'Satkhira', bnName: 'সাতক্ষীরা' },
  // Mymensingh
  { id: '41', divisionId: '8', name: 'Jamalpur', bnName: 'জামালপুর' },
  { id: '42', divisionId: '8', name: 'Mymensingh', bnName: 'ময়মনসিংহ' },
  { id: '43', divisionId: '8', name: 'Netrokona', bnName: 'নেত্রকোণা' },
  { id: '44', divisionId: '8', name: 'Sherpur', bnName: 'শেরপুর' },
  // Rajshahi
  { id: '45', divisionId: '3', name: 'Bogura', bnName: 'বগুড়া' },
  { id: '46', divisionId: '3', name: 'Joypurhat', bnName: 'জয়পুরহাট' },
  { id: '47', divisionId: '3', name: 'Naogaon', bnName: 'নওগাঁ' },
  { id: '48', divisionId: '3', name: 'Natore', bnName: 'নাটোর' },
  { id: '49', divisionId: '3', name: 'Chapai Nawabganj', bnName: 'চাঁপাইনবাবগঞ্জ' },
  { id: '50', divisionId: '3', name: 'Pabna', bnName: 'পাবনা' },
  { id: '51', divisionId: '3', name: 'Rajshahi', bnName: 'রাজশাহী' },
  { id: '52', divisionId: '3', name: 'Sirajganj', bnName: 'সিরাজগঞ্জ' },
  // Rangpur
  { id: '53', divisionId: '7', name: 'Dinajpur', bnName: 'দিনাজপুর' },
  { id: '54', divisionId: '7', name: 'Gaibandha', bnName: 'গাইবান্ধা' },
  { id: '55', divisionId: '7', name: 'Kurigram', bnName: 'কুড়িগ্রাম' },
  { id: '56', divisionId: '7', name: 'Lalmonirhat', bnName: 'লালমনিরহাট' },
  { id: '57', divisionId: '7', name: 'Nilphamari', bnName: 'নীলফামারী' },
  { id: '58', divisionId: '7', name: 'Panchagarh', bnName: 'পঞ্চগড়' },
  { id: '59', divisionId: '7', name: 'Rangpur', bnName: 'রংপুর' },
  { id: '60', divisionId: '7', name: 'Thakurgaon', bnName: 'ঠাকুরগাঁও' },
  // Sylhet
  { id: '61', divisionId: '6', name: 'Habiganj', bnName: 'হবিগঞ্জ' },
  { id: '62', divisionId: '6', name: 'Moulvibazar', bnName: 'মৌলভীবাজার' },
  { id: '63', divisionId: '6', name: 'Sunamganj', bnName: 'সুনামগঞ্জ' },
  { id: '64', divisionId: '6', name: 'Sylhet', bnName: 'সিলেট' },
];
